# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details


version: 2.1
# orbs:
  # codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.9.2

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install
          command: |
            conda install -c conda-forge openmc==0.13.0
            pip install .[density,tests]
 
      # run tests!
      - run:
          name: run tests
          command:
            pytest tests -v --cov=neutronics_material_maker --cov-report term --cov-report html:htmlcov --cov-report xml --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
      - run:
          name: install curl
          command: |
            apt-get --allow-releaseinfo-change update
            apt-get update && apt-get -y install curl
      - run: curl -s https://codecov.io/bash | bash
