# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details


version: 2.1
# orbs:
  # codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: openmcworkshop/openmc_workshop_dependencies:openmc_nndc
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install
          command:
            python setup.py install
      # - run: docker build -t shimwell/paramak:latest . 
      # - run: xhost local:root
      # - run: docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -v $PWD:/home -e DISPLAY=unix$DISPLAY --privileged shimwell/paramak
 
      # run tests!
      - run:
          name: run tests
          command: 
            pytest tests -v --cov=neutronics_material_makergit  --cov-report term --cov-report html:htmlcov --cov-report xml --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          # destination: test-reports
      - run:
          name: install curl
          command:
            apt-get update && apt-get install curl
      - run: curl -s https://codecov.io/bash | bash
      # - codecov/upload:
          # file: {{ coverage_report_filepath }}
